CHANGELOG.md, README.md, config.schema.json, package.json, src/platform.ts, src/platformAccessory.ts
⚠️ This is a BREAKING change, as the configuration JSON has been sligthly changed.
=> Exclude keys for a specific device (fix #12)

CHANGELOG.md, docs/install.md, package-lock.json, package.json, src/platform.ts
Added an error log message if the version is too old.
Also checking the "legacy" topic `bridge/config` (next to the "new" topic `bridge/info`).
=> Bump minimum zigbee2mqtt version to v1.17.0

CHANGELOG.md, config.schema.json, docs/action.md, docs/config.md, docs/converters.md, src/configModels.ts, src/converters/action.ts, src/converters/action_helper.ts, src/converters/creators.ts, src/converters/interfaces.ts, src/platform.ts, src/platformAccessory.ts, test/action.spec.ts, test/action_helper.spec.ts, test/basic_sensors.spec.ts, test/cover.spec.ts, test/light.spec.ts, test/switch.spec.ts, test/testHelpers.ts
=> Support for push buttons (Stateless Programmable Switch)

CHANGELOG.md, src/converters/light.ts, test/light.spec.ts
=> Fix: Color change of lights using color_hs was not sent correctly

.github/workflows/build.yml
Attempt at fixing PR builds from forks.
=> Fix PR builds from forks

CHANGELOG.md, src/converters/light.ts, src/platform.ts, test/light.spec.ts
=> Set range of Color Temperature characteristic

CHANGELOG.md, src/converters/action.ts, src/converters/basic_sensors.ts, src/converters/battery.ts, src/converters/climate.ts, src/converters/cover.ts, src/converters/creators.ts, src/converters/interfaces.ts, src/converters/light.ts, src/converters/lock.ts, src/converters/monitor.ts, src/converters/switch.ts, src/platformAccessory.ts
=> Update Service Name if friendly_name is updated

CHANGELOG.md, src/converters/cover.ts, test/cover.spec.ts
This will hopefully also resolve #189
=> Minor tweaks to cover handler

CHANGELOG.md, src/platform.ts
Added a warning if an incorrect output format is detected as this has resulted in bug reports multiple times.
=> Warning if an incorrect output format is detected

CHANGELOG.md, src/converters/basic_sensors.ts, src/converters/climate.ts, src/helpers.ts
Also set minimum value for Ambient Light Level to 0, if range is not provided (should solve #235)
=> Take over numeric range for "passthrough" characteristics

CHANGELOG.md, docs/cover.md, docs/devices/current_products_corp/cp180335e-01.md, docs/devices/index.md, src/converters/cover.ts, test/cover.spec.ts
Should add support for Current Products Corp CP180335E-01 (fixes #254)
=> Support for cover devices that only expose tilt

CHANGELOG.md, src/platform.ts
=> Only log Zigbee2MQTT version on change

CHANGELOG.md, config.schema.json, docs/config.md, docs/howitworks.md, src/configModels.ts, src/docgen/docs_accessory.ts, src/experimental.ts, src/platform.ts, src/platformAccessory.ts, src/z2mModels.ts, test/exposes_overlap.spec.ts
=> Support for groups

CHANGELOG.md, src/platform.ts, src/z2mModels.ts, test/exposes_overlap.spec.ts
=> Additional changes for supporting groups

CHANGELOG.md, docs/config.md, src/platform.ts
=> Ignore exclude: false in defaults configuration

CHANGELOG.md, docs/config.md, docs/install.md, src/configModels.ts, src/platformAccessory.ts
=> Add included_keys to device configuration

CHANGELOG.md, docs/config.md, src/experimental.ts, src/platform.ts
After this, we can resolve #277
=> Support for groups no longer requires experimental configuration

CHANGELOG.md, src/converters/climate.ts, src/converters/light.ts, src/converters/lock.ts, src/converters/switch.ts, src/z2mModels.ts
=> Do more checks before trying to create the ServiceHandler

.gitignore, src/docgen/docgen.ts, test/action.spec.ts, test/air_quality.spec.ts, test/basic_sensors.spec.ts, test/cover.spec.ts, test/exposes/current_products_corp/cp180335e-01.json, test/exposes/danalock/v3-btzb_v3-btzbe.json, test/exposes/heiman/hs1vs-n.json, test/exposes/ikea/e1603_e1702_e1708.json, test/exposes/ikea/e1766.json, test/exposes/ikea/e1926.json, test/exposes/insta/57008000.json, test/exposes/oujiabao/cr701-yz.json, test/exposes/smartthings/stss-pres-001.json, test/exposes/ubisys/s2.json, test/exposes/xiaomi/mccgq11lm.json, test/exposes/xiaomi/rtcgq11lm.json, test/exposes/xiaomi/vockqjk11lm.json, test/exposes/xiaomi/wsdcgq12lm.json, test/exposes/xiaomi/wxcjkg13lm.json, test/lock.spec.ts, test/switch.spec.ts, test/testHelpers.ts
Unfortunately not all tests have been updated yet as some tests failed when trying to use the latest exposes information.
These will require further investigation and changes.
=> Use JSON files as input for the tests, so they can be updated easier.

CHANGELOG.md, src/converters/climate.ts, src/converters/light.ts, src/converters/lock.ts, src/converters/switch.ts
=> Bind accessory.isPropertyExcluded correctly

CHANGELOG.md, src/converters/cover.ts, src/z2mModels.ts, test/cover.spec.ts
=> Window Covering can now be requested to stop moving

CHANGELOG.md, config.schema.json, docs/config.md, src/configModels.ts, src/platform.ts
=> Make log level for published MQTT messages configurable

CHANGELOG.md, docs/config.md, src/experimental.ts, src/platformAccessory.ts
=> Move Availability feature behind an experimental feature flag

CHANGELOG.md, docs/light.md, src/converters/light.ts
Add the ability to have the integration only send Color Temperature updates when the light is on, and additionally, have it send a `transition` along with the Color Temperature.
=> Adaptive Lighting: Only when light is on + Transition
